spring.application.name=home-inventory-helper-bot
spring.datasource.url=jdbc:postgresql://localhost:5432/home-inventory
spring.datasource.username=${POSTGRESDB_USER}
spring.datasource.password=${POSTGRESDB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

